CREATE DATABASE IF NOT EXISTS tech_house;
USE tech_house;

CREATE TABLE IF NOT EXISTS roles(
id INT NOT NULL AUTO_INCREMENT,
name VARCHAR(100) NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS users(
id INT NOT NULL AUTO_INCREMENT,
name VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL,
password VARCHAR(65) NOT NULL,
country VARCHAR(45),
avatar VARCHAR(100),
id_role INT NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (id_role) REFERENCES roles (id)
)ENGINE InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS categories(
id INT NOT NULL AUTO_INCREMENT,
name VARCHAR(100) NOT NULL,
PRIMARY KEY (id)
)ENGINE InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS products(
id INT NOT NULL AUTO_INCREMENT,
name VARCHAR(200) NOT NULL,
specifications TEXT,
warranty_text VARCHAR(450),
warranty_time INT NOT NULL,
price DOUBLE NOT NULL,
discount DOUBLE,
quota VARCHAR(100),
shipping DOUBLE NOT NULL,
return_value DOUBLE NOT NULL,
id_category INT NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (id_category) REFERENCES categories (id)
)ENGINE InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS payment_methods(
id INT NOT NULL AUTO_INCREMENT,
name VARCHAR(100) NOT NULL,
image VARCHAR(100) NOT NULL,
PRIMARY KEY (id)
)ENGINE InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS products_payment_methods(
id INT NOT NULL AUTO_INCREMENT,
id_product INT NOT NULL,
id_payment_method INT NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (id_product) REFERENCES products (id),
FOREIGN KEY (id_payment_method) REFERENCES categories (id)
)ENGINE InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS images(
id INT NOT NULL AUTO_INCREMENT,
image VARCHAR(100),
id_product INT NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (id_product) REFERENCES products (id)
)ENGINE InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS color(
id INT NOT NULL AUTO_INCREMENT,
color VARCHAR(100) NOT NULL,
id_product INT NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (id_product) REFERENCES products (id)
)ENGINE InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS characteristics(
id INT NOT NULL AUTO_INCREMENT,
title VARCHAR(100) NOT NULL,
id_product INT NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (id_product) REFERENCES products (id)
)ENGINE InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS characteristics_main(
id INT NOT NULL AUTO_INCREMENT,
subtitle VARCHAR(200) NOT NULL,
description TEXT NOT NULL,
id_characteristic INT NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (id_characteristic) REFERENCES characteristics (id)
)ENGINE InnoDB DEFAULT CHARSET=utf8mb4;

